# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 18:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=254)),
                ('guid', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ('name',),
                'permissions': (('read_portalinfo', 'Allowed to see the list of discovered portals'),),
            },
        ),
        migrations.CreateModel(
            name='DiscovererUser',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'permissions': (('read_original_index', 'Allowed to fetch the original index'), ('read_entire_index', 'Allowed to fetch the original index augmented by new portals')),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='portalinfo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
