# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discoverer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portalinfo',
            unique_together=set([('lat', 'lng')]),
        ),
    ]
