# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discoverer', '0003_auto_20170606_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='KmlOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254)),
                ('kmlfile', models.FileField(upload_to=b'kml/output')),
                ('portal_count', models.PositiveIntegerField(unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-portal_count',),
                'permissions': (('read_kmloutput', 'Allowed to download the kml'),),
            },
        ),
    ]
