# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoverer', '0005_auto_20170607_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalinfo',
            name='stored_county',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
