# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoverer', '0007_auto_20170611_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovereruser',
            name='discovered_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discovereruser',
            name='updated_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
