# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 01:08
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations.operations.special import noop
from pymongo.errors import BulkWriteError

from discoverer.portalindex.helpers import MongoPortalIndex, PortalIndexHelper


def copy_portalinfo_into_mongodb(apps, schema_editor):
    PortalInfo = apps.get_model('discoverer', 'PortalInfo')
    for pi in PortalInfo.objects.all():
        doc = {
            'location': {
                "type": "Point",
                "coordinates": [float(pi.lng), float(pi.lat)]
            },
            'name': pi.name,
            'timestamp': pi.created_at,
            'reporter': pi.created_by.username,
        }
        doc['_ref'] = PortalIndexHelper.sha_hash(doc)
        doc['_history'] = [doc.copy()]

        MongoPortalIndex.bulk_op.insert(doc)

    try:
        results = MongoPortalIndex.bulk_op_execute()
    except BulkWriteError as e:
        print e.details
        raise e


class Migration(migrations.Migration):

    dependencies = [
        ('discoverer', '0007_auto_20170614_1751'),
    ]

    operations = [
        migrations.RunPython(copy_portalinfo_into_mongodb, reverse_code=noop)
    ]
