# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 01:08
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations.operations.special import noop
from pymongo.errors import BulkWriteError

from discoverer.portalindex.helpers import MongoPortalIndex, PortalIndexHelper


# moved to management.commands.import_from_portalinfo


class Migration(migrations.Migration):

    dependencies = [
        ('discoverer', '0007_auto_20170614_1751'),
    ]

    operations = [
        migrations.RunPython(noop, reverse_code=noop)
    ]
