# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 02:39
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations.operations.special import noop


def update_user_counts_from_portalinfo(apps, schema_editor):
    DiscovererUser = apps.get_model('discoverer', 'DiscovererUser')
    PortalInfo = apps.get_model('discoverer', 'PortalInfo')
    for user in DiscovererUser.objects.all():
        user.discovered_count = PortalInfo.objects.filter(created_by=user).count()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('discoverer', '0008_auto_20170614_1808'),
    ]

    operations = [
        migrations.RunPython(update_user_counts_from_portalinfo, reverse_code=noop)
    ]
