# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discoverer', '0010_searchregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254)),
                ('filetype', models.CharField(default=b'kml', max_length=254)),
                ('file', models.FileField(upload_to=b'dataset-output/')),
                ('portal_index_etag', models.CharField(max_length=254)),
                ('config_hash', models.CharField(max_length=254)),
                ('stored_config_kwargs', models.TextField()),
                ('status', models.CharField(choices=[(b'building', b'Building'), (b'ready', b'Ready')], default=b'building', max_length=254)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': (('read_kmloutput', 'Allowed to download the dataset'),),
            },
        ),
        migrations.RemoveField(
            model_name='kmloutput',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='kmloutput',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='KmlOutput',
        ),
        migrations.AlterUniqueTogether(
            name='datasetoutput',
            unique_together=set([('portal_index_etag', 'config_hash')]),
        ),
    ]
